- name: MySQL server configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.laven.cloud
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present
    
    - name: Start and enable MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Connect to MySQL server
      community.mysql.mysql_info:
        login_host: "{{ login_host }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
      ignore_errors: yes
      register: mysql_info
      
    - name: Install PyMySQL module using pip
      ansible.builtin.pip:
        - PyMySQL
      executable: pip3.9

    - name: Print MySQL information
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"

       
